paucibot:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 150

    wheel1_position_controller:
        type: effort_controllers/JointPositionController
        joint: wheel1_link
        pid: {p: 100.0, i: 0.01, d: 10.0} 

    wheel2_position_controller:
        type: effort_controllers/JointPositionController
        joint: wheel2_link
        pid: {p: 100.0, i: 0.01, d: 10.0}
